### ISSUE TITLE
v0.11.5 requires git to be installed

### ISSUE THREAD

**Issue by jealousofyou** [mfkrause/homebridge-people-pro#17]
While updating from v0.11.4 to v0.11.5, I got an error when homebridge was running `sudo -E -n npm install -g homebridge-people-pro@latest` via the plugin's "UPDATE" button in the UI. The npm log file showed this:

    162 verbose Linux 5.4.83-v7+
    163 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-people-pro@latest"
    164 verbose node v14.16.1
    165 verbose npm  v6.14.12
    166 error code ENOENT
    167 error syscall spawn git
    168 error path git
    169 error errno -2
    170 error enoent Error while executing:
    170 error enoent undefined ls-remote -h -t ssh://git@github.com/mfkrause/local-devices.git
    170 error enoent
    170 error enoent
    170 error enoent spawn git ENOENT
    171 error enoent This is related to npm not being able to find a file.

My system:
- Pi 3b, running buster
- Homebridge: v1.3.4, installed as per the instructions at https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian
- Node.js: v14.16.1, recently updated from v14.16.0 to satisfy a dependency from homebridge-hue v0.13.8
- Npm: v6.14.12

Some quick googling indicated that the error was caused by `git` not being present on my system. After running `sudo apt install git` I could successfully install the homebridge-people-pro plugin.

**Comment by mfkrause** [comment]
Sorry, unthoughtful update of mine. This should be fixed with v0.11.6. Thanks for the report!
