### ISSUE TITLE
Feature request: Custom DNS Entry

### ISSUE THREAD

**Issue by ppapajohn** [mfkrause/homebridge-people-pro#8]
Hi @mfkrause, 
thank you for the great plugin! Unfortunately I cannot use it the way I have setup my home network. In a nutshell, I have a RaspberryPi4, on which I have installed Pi-Hole (amazing project!) and Homebridge. The OS is an Ubuntu 20.04.2 LTS. 

As such, the DNS server on the OS is not Pi-Hole, but Cloudfare's DNS servers. So, if I add the phone's name in the config.json file instead of the IP, this never gets resolved. Obviously an option would be to assign a static IP on all phones, however, this would be time consuming as you can imagine. 

So, it would be great to add an option for custom DNS server, so as to redirect or A record queries to Pi-Hole. 

Hope this makes sense. Wishes for a great (rest of the) weekend ahead! :) 

Best Regards,
Panos

**Comment by mfkrause** [comment]
Hey! Thanks for the feature request.

Based on your explanation, I feel like this is a very specific use-case. However, as the implementation should be relatively easy, I'll see if I can get this implemented by next week.

**Comment by ppapajohn** [comment]
Thanks @mfkrause! Looking forward to it! :) 

Although it may sound a specific request, many people combine projects on a pi. Besides rpi4 is very powerful and it can easily cope with both. Since pi-hole is another very popular project on the pi, such a combination is very often to the best of my knowledge; maybe other can benefit as well! :)

take care and wishes for a great week ahead!

**Comment by infernalK** [comment]
Hello,
I’m also interested in this update cause I have the same issue with PiHole.

**Comment by mfkrause** [comment]
@ppapajohn @infernalK Hi there, this is now implemented in v0.10.0. Custom DNS servers can be added per target using the "customDns" property (please refer to the README or configure using homebridge-config-ui-x).
If you have any questions or problems with this version, please let me know.

**Comment by ppapajohn** [comment]
Don’t know if this will reach u. Thank you very much mfkrause! Much appreciated! :) 


On 3 Mar 2021, at 21:59, Maximilian Krause <notifications@github.com> wrote:

﻿
@ppapajohn @infernalK Hi there, this is now implemented in v0.10.0. Custom DNS servers can be added per target using the "customDnsServer" property (please refer to the README or configure using homebridge-config-ui-x).
If you have any questions or problems with this version, please let me know.

**Comment by infernalK** [comment]
Hello, 
Thanks for the update.
It’s working good for me except for one device (Samsung S20). It’s Ok with Samsung S41 and IPhone.

**Comment by ppapajohn** [comment]
thank you @mfkrause! Much appreciated! So far all good.. I will test it a bit more during the weekend. 
Have a great day ahead! :)
