### ISSUE TITLE
Future Request: Add User my MAC address

### ISSUE THREAD

**Issue by monza258** [mfkrause/homebridge-people-pro#9]
Hi, thanks for develop people-pro plugin. Looks very nice. 

Can you include the option to add target by "MAC" address?

**Comment by mfkrause** [comment]
Hey! This is already on the to-do list and should be implemented by the end of next week.

**Comment by mfkrause** [comment]
Hi there, this is now supported (#11). Please update the plugin to v0.11.0.
To use it, simply use a MAC address in the network as a target. The plugin will lookup the corresponding IP address.

If you have any questions or problems with this update, let me know.
